language: node_js
node_js:
  - "4.1"

install:
  - npm install -g elm@0.16.0 casperjs http-server
  - elm-package install -y
before_script:
  - elm-make --yes --output raw-test.js elm/TestRunner.elm
  - bash elm-stuff/packages/laszlopandy/elm-console/1.0.2/elm-io.sh raw-test.js test.js

script: node test.js
